{% set name = "pygit2" %}
{% set version = "1.5.0" %}
{% set sha256 = "9711367bd05f96ad6fc9c91d88fa96126ba2d1f1c3ea6f23c11402c243d66a20" %}

# must pin the appropiate libgit2 version documented here:
# https://www.pygit2.org/install.html#version-numbers

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}

  host:
    - python
    - pip
    - cffi
    - libgit2 1.1.*

  run:
    - python
    - cached-property
    - cffi
    - six
    - libgit2 1.1.*

test:
  imports:
    - pygit2

about:
  home: http://github.com/libgit2/pygit2
  summary: Python bindings for libgit2.
  license: GPL-2.0-only WITH GCC-exception-2.0
  license_family: GPL
  license_file: COPYING
  doc_url: http://www.pygit2.org/
  dev_url: https://github.com/libgit2/pygit2

extra:
  recipe-maintainers:
    - kszucs
    - xhochy
