{% set name = "pygit2" %}
{% set version = "1.2.1" %}
{% set sha256 = "de9421118a99c79cbba1e512d60e5caed1d63273ce30a0e8d4edef4a2e500387" %}

# must pin the appropiate libgit2 version documented here:
# https://www.pygit2.org/install.html#version-numbers

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  features:
    - vc10   # [win and py34]
    - vc14   # [win and py35]
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}

  host:
    - python
    - pip
    - cffi
    - libgit2 1.0.*

  run:
    - python
    - cached-property
    - cffi
    - six
    - libgit2 1.0.*

test:
  imports:
    - pygit2

about:
  home: http://github.com/libgit2/pygit2
  summary: Python bindings for libgit2.
  license: GPL-2.0 WITH GCC-exception-2.0
  license_family: GPL
  license_file: COPYING
  doc_url: http://www.pygit2.org/
  dev_url: https://github.com/libgit2/pygit2

extra:
  recipe-maintainers:
    - kszucs
    - xhochy
