# must pin the appropiate libgit2 version documented here:
# https://www.pygit2.org/install.html#version-numbers
schema_version: 1

context:
  version: "1.18.2"

package:
  name: pygit2
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pygit2/pygit2-${{ version }}.tar.gz
  sha256: eca87e0662c965715b7f13491d5e858df2c0908341dee9bde2bc03268e460f55

build:
  number: 2
  skip: match(python, "<3.10")

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - cffi
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - cffi
    - libgit2 1.9.*
  run:
    - python
    - cffi

tests:
  - python:
      imports:
        - pygit2
      pip_check: true

about:
  summary: Python bindings for libgit2.
  license: GPL-2.0-only WITH GCC-exception-2.0
  license_file: COPYING
  homepage: http://github.com/libgit2/pygit2
  repository: https://github.com/libgit2/pygit2
  documentation: http://www.pygit2.org/

extra:
  recipe-maintainers:
    - efiop
    - kszucs
    - xhochy
