appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: eSbmQWTC86kW1jdKvpBO33t5fLA8giPC8U0Y+/k9zhSBa1MjQOWB1Mg73veAzAKPvQJXjkxoxC5VU9N0OF7zD3ODc/2ocoz+oq513MmGzUNqfKQWusgCBRN/7GPOee74Akdtt54XgTYYeTpCSfX1b5Lc+cb+uBJq42S96RGRzcgHBXQ0X3zuIpYMuo7wCWQOmn4fl1NcNK+fGSJRr+vo3PYT9eniWFEvywGO/XCQzFlnKU7HOMhE70VTAqv+YL+LnUyYhDbaAsVyWVPdpWBOZd4L/mBBbAFyvg2tqxSb8L3ZXe12wFKJClVOcleP/6P75F8iRmRqjdqmXK4CZMeEWEQ0cKkZWbTp2gOZ5IrDLS2eBUHSAv0uMBX28reOYVzFiTlrOHejdFbVpUh/KaSqTyy9ALpETy3PXs53UOW7hCVPg5PxfiBZZr0vfmmIVN+YclsssG9yU5XhADvtBsLzJniOQwt/ZlPOcYiy/9VQbwl0evvcjxV5N5kUIUTkZ1AuTLVWLRFWL7kpZHRcMCBJG9n5cPX/p/dx20yo4R9Owou3tQIo0D/3lqlbsiBLl2KHNHXsSMddsFfz2yPDkBZKXKRyx3NEMj+ILbIRbErzbOZos7eFS2l48CvzjKn6yhFOA5mnPKGGgAJIDAQvKdsQ3ZVfRE8D4RzxwawJ+AVHPmc=}
provider:
  win: azure
